spring.application.name=banking-exchange-system
grpc.server.port=9090
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.graphql.graphiql.enabled=true

grpc.client.exchangeClient.address=static://127.0.0.1:9090
grpc.client.exchangeClient.negotiationType=plaintext